services:
  api1:
    image: ghcr.io/lucianopf/rinha-de-backend-2026-go:v10
    command: ["./server", "--port", "8080", "--model", "resources/model.bin"]
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150MB"
    networks: [rinha]
  api2:
    image: ghcr.io/lucianopf/rinha-de-backend-2026-go:v10
    command: ["./server", "--port", "8080", "--model", "resources/model.bin"]
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150MB"
    networks: [rinha]
  lb:
    image: ghcr.io/lucianopf/rinha-de-backend-2026-go:v10
    command: ["./lb", "--listen", ":9999"]
    ports: ["9999:9999"]
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"
    networks: [rinha]
networks:
  rinha:
    driver: bridge
