services:
  api1:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150MB"
    networks:
      - rinha
    restart: unless-stopped

  api2:
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        limits:
          cpus: "0.45"
          memory: "150MB"
    networks:
      - rinha
    restart: unless-stopped

  lb:
    build:
      context: .
      dockerfile: Dockerfile.lb
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "50MB"
    networks:
      - rinha
    depends_on:
      - api1
      - api2

networks:
  rinha:
    driver: bridge
